export enum PermissionEnum {
  APP_READ = 'APP_READ',

  USER_READ = 'USER_READ',
  USER_READ_OTHER = 'USER_READ_OTHER',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_UPDATE_OTHER = 'USER_UPDATE_OTHER',
  USER_ACTIVATE = 'USER_ACTIVATE',
  USER_DEACTIVATE = 'USER_DEACTIVATE',

  ROLE_READ = 'ROLE_READ',
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',

  PERMISSION_READ = 'PERMISSION_READ',

  RBAC_LINK_PERM_ROLE = 'RBAC_LINK_PERM_ROLE',
  RBAC_LINK_ROLE_USER = 'RBAC_LINK_ROLE_USER',
  RBAC_LINK_PERM_USER = 'RBAC_LINK_PERM_USER',
  RBAC_LINK_USER_APP = 'RBAC_LINK_USER_APP',

  PROFILE_READ = 'PROFILE_READ',
  PROFILE_READ_OTHER = 'PROFILE_READ_OTHER',
  PROFILE_UPDATE = 'PROFILE_UPDATE',
  PROFILE_UPDATE_OTHER = 'PROFILE_UPDATE_OTHER',
}
